### ISSUE TITLE
[Bug ?] False positive with health check ?

### ISSUE THREAD

**Issue by charnould** [mrsked/mrsk#187]
I'm not sure it's a bug.  
If needed, I could try to document it much more precisely, but below the "story"

- I was trying to deploy with MRSK, everything was "MRSK successful" in my terminal (weirdly !) but my app (a simple NodeJS Hello World) was returning a `404`.
- After digging into containers logs, Traefik told me that a `port` was missing.  
   Indeed, there was NO `EXPOSE 3000` in my Dockerfile. Fixing this makes my deployment successful 👍 . 
- **But** how can MRSK health check might have been "MRSK successful" if my app was down (remember the 404 above)?

**Comment by tannakartikey** [comment]
@charnould MRSK spins up a new container for the health check (notice the code below). While running this command, MRSK exposes `3000` or the port mentioned in the config. 

https://github.com/mrsked/mrsk/blob/2146f6d0ecbdc675226daabd5a3dcaa0ce389e0f/lib/mrsk/commands/healthcheck.rb#L7-L17

So I think what happened was that while health check the port was exposed but it was not exposed to Traefik. That's why you got the success message.

**Comment by charnould** [comment]
Thanks! But is this a bug or a feature? :-)  
I mean: it's certainly note to MRSK to check if my Dockerfile is well-formatted, but here MRSK tells me everything is ok whereas it's not (= my app is down).

**Comment by tannakartikey** [comment]
@charnould I would say it's just implementation details? Maybe we can check if the port mentioned in the config file is actually exposed or not. The `docker port` command can be handy here.

**Comment by charnould** [comment]
I'll be glad to contribute but I'm not at all a Ruby/Docker guy (at max a JS newbie...). Sorry.
Feel free to close this issue and thanks a lot for your explanation.
