### ISSUE TITLE
curl removed from healthcheck -- breaking all new deploys

### ISSUE THREAD

**Issue by 34code** [mrsked/mrsk#276]
reverting to version `0.12.0` does not fix
reverting to version `0.11.0` fixes it

Seems like `healthcheck` uses `curl` and removing it from the container doing the healthcheck is breaking things.

**Comment by 34code** [comment]
https://en.wikipedia.org/wiki/Up_to_eleven

The power of 11 !!

**Comment by dhh** [comment]
cc @kevinmcconnell @djmb

**Comment by giedriusr** [comment]
Wanted to open an issue as well. @34code was faster 👍🏻  0.12 doesn't work, 0.11 works.

**Comment by djmb** [comment]
@34code, @giedriusr - since version 0.12.0, [mrsk uses docker healthchecks to wait for the container to become healthy](https://github.com/mrsked/mrsk/blob/main/README.md#healthcheck). 

The check to run is passed via the [--health-cmd option to docker run](https://docs.docker.com/engine/reference/commandline/run/).

This allows Traefik to monitor the status of the container and wait for it to report that it is healthy.

The effect of all of this is that the healthcheck command is now run by docker *inside* the container and not by mrsk from the host VM. The default healthcheck command uses curl to check if the app is up.

So you should either:
1. Install curl in your container
2. Or specify a custom healthcheck command via the config (see example [here](https://github.com/mrsked/mrsk/blob/54881a0298b516cb315b90c55b2298b808c3bfb5/test/integration/docker/deployer/app/config/deploy.yml#L12-L13))

**Comment by jasonfb** [comment]
@34code -- could you kindly clarify precisely what you mean by "breaking things"? 
what is the error you are seeing?

**Comment by 34code** [comment]
The error is `curl not found` and results in healthcheck failing

**Comment by 34code** [comment]
Here are the exact error logs from `v0.12.0`

```ERROR {
  "Status": "unhealthy",
  "FailingStreak": 2,
  "Log": [
    {
      "Start": "2023-05-06T21:22:22.780823251Z",
      "End": "2023-05-06T21:22:22.839109929Z",
      "ExitCode": 1,
      "Output": "/bin/sh: 1: curl: not found\n"
    },
    {
      "Start": "2023-05-06T21:22:23.841660285Z",
      "End": "2023-05-06T21:22:23.904228706Z",
      "ExitCode": 1,
      "Output": "/bin/sh: 1: curl: not found\n"
    }
  ]
}```

**Comment by 34code** [comment]
> I recommend 1.
> 
> Add curl exactly here and it will work.
> 
> https://gist.github.com/PabloC/085024b94c58f473ea6c983231705421#file-gistfile1-txt-L66

I tried this and it does not fix the problem.

**Comment by 34code** [comment]
I was able to "fake" a healthcheck by using the custom healthcheck parameter in `deply.yml` by using:

```
healthcheck:
  cmd: ls -l > /dev/null
```

Obviously this is NOT the way to go.. so happy to help fix the appropriate dockerfile if someone can point me in the right direction..

**Comment by Jberczel** [comment]
Can you confirm curl installed in your container?  Seems like you still didn't install.

```
mrsk app exec 'curl --version'
```

**Comment by 34code** [comment]
```docker stderr: /rails/bin/docker-entrypoint: line 8: exec: curl: not found```

**Comment by 34code** [comment]
ok I added `curl` to the apt-get install line in the dockerfile and now the container shows curl as being installed:

`mrsk app exec 'curl --version'`

```curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09```

thanks for pointing me in the right direction, @Jberczel !

**Comment by 34code** [comment]
> I recommend 1.
> 
> Add curl exactly here and it will work.
> 
> https://gist.github.com/PabloC/085024b94c58f473ea6c983231705421#file-gistfile1-txt-L66

my bad, seems like i did not try this properly the first time.. Perhaps we should update the default dockerfile to have `curl` installed? For those who are not going to use a custom healthcheck command..

**Comment by defp** [comment]
Install curl in container solve the problem
