### ISSUE TITLE
Docker -> Podman ?

### ISSUE THREAD

**Issue by sebastian0x62** [mrsked/mrsk#61]
Thoughts about supporting Podman instead of Docker as well?

**Comment by dhh** [comment]
Happy to see someone explore it. Don't personally have an interest in doing the work, but Please Do Investigate 👍

**Comment by shobhitic** [comment]
I am exploring it right now!

**Comment by srbaker** [comment]
Any movement on this?  Is there any way I can help?

**Comment by brandondrew** [comment]
> Any movement on this? Is there any way I can help?

@srbaker Perhaps you could make the offer on @phoozle's [project](https://github.com/phoozle/kamal_podman/).  It would be great to have your support behind this!

**Comment by braun2morrow** [comment]
I've been toying a bit with kamal to see how far I can get with `sudo ln -s /usr/bin/podman /usr/bin/docker` on the production server:

1. Podman complains about the insecure registry. Fixed by:
> vi  ~/.config/containers/registries.conf.d/localhost-insecure.conf
>         [[registry]]
>         location = "localhost:5555"
>         insecure = true

2. Not sure why, but I've had to run `podman network create kamal` manually.
3. Then kamal fails to get the kamal-proxy image, and breaks if we provide one with the default "latest" version, so we need to figure it out manually:
`podman search --list-tags  docker://docker.io/basecamp/kamal-proxy | sort --version-sort`
`podman create --replace --name=kamal-proxy docker://docker.io/basecamp/kamal-proxy:$VERSION`
Maybe something like this will bite again whenever the kamal-proxy image gets updated. But that would be no dealbreaker, so let's go on:

4. Since everything runs as non-root (and we can't setcap the kamal-proxy binary in the container), kamal-proxy needs to listen on unprivileged ports. Manually starting it works:
`podman run kamal-proxy   kamal-proxy run --http-port 8080 --https-port 4443`
However, I've had issues with kamal not finding that instance. Investigating this is probably the best way forward if you want to run kamal and the kamal-proxy image unmodified.
But since kamal wants to admin the kamal-proxy, maybe we can simply put

> proxy:
>   run:
>     http_port: 8080
>     https_port: 4443

  into deploy.yml and kamal will DTRT? Turns out: no. I'd expected that setting would lead to kamal executing
`docker run … kamal-proxy run kamal-proxy run --http-port 8080 --https-port 4443`
but instead it does
`docker run … --publish 8080:80 --publish 4443:443  kamal-proxy run`
and that obviously still fails because kamal-proxy still can't listen on 80 and 443. Fixing that in the kamal source ought to be fairly straightforward.

I feel that this is quite close to working (did I mention that the app container gets deployed and runs fine?), but that's as far as I got, and unless my betters decide that we should adopt kamal, I can't spend any more company time on it. Good luck!
