### ISSUE TITLE
Suggestion: Some sort of mechanism for using auto-scaling cloud VMs

### ISSUE THREAD

**Issue by nickchomey** [mrsked/mrsk#74]
The readme suggests that you can `buy the baseline with your own hardware, then deploy to a cloud before a big seasonal spike to get more capacity.` 

I could very well be missing some functionality or the broader goal here, but it is my impression that there isn't any kubernetes-like autoscaling capabilities in MRSK - it is meant for just deploying containers to a fixed set of machines, therefore that seasonal-cloud VM still needs to be manually deployed and scaled.

If this is the case, it would be wonderful if you could use cloud providers' auto scaling mechanisms (e.g. Azure VM Scale Sets) so as to have a static baseline of owned or rented bare metal servers, but then also have the flexibility of the cloud to meet unexpected traffic spikes. After the spike, you could deploy more bare metal according to how much of the new traffic might stick around.

**Comment by dhh** [comment]
I think that's going to be outside the scope of what we're doing with MRSK. There is no running daemon, and there will be no running daemon, for MRSK. This is a tool that instruments basic Docker.

So that line, buying the baseline and renting the spike, is for spikes you can either anticipate or react quickly with. If you have totally unpredictable spikes that might happen at any second, you probably should look at a k8s solution or similar.

**Comment by dhh** [comment]
I don't think this has anything to do with mission critical or not. Basecamp is mission critical. It's never had auto scaling. HEY is mission critical. Ditto.

And exactly as you say, we just monitor our services. If they're seeing high load, we add resources.

Happy to see more discussion happen. I've opened https://github.com/mrsked/mrsk/discussions for that purpose. Feel free to start a discussion there 👍
